name: Deploy to Dokku

on: workflow_dispatch
# on:
#   push:
#     branches:
#       - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Push to Dokku
              uses: dokku/github-action@master
              with:
                  git_push_flags: "--force"
                  git_remote_url: "ssh://dokku@bene.dev/template"
                  ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
